# Generated by Django 4.1.1 on 2022-09-28 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projectmanager", "0004_alter_project_due_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="completed",
            field=models.BooleanField(default=False),
        ),
    ]
