# Generated by Django 4.1.1 on 2022-09-28 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("projectmanager", "0006_project_date_completed"),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=30)),
                ("description", models.TextField()),
                ("due_date", models.DateField(blank=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("completed", models.BooleanField(default=False)),
                ("date_completed", models.DateTimeField(blank=True, null=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projectmanager.project",
                    ),
                ),
            ],
        ),
    ]
