# Generated by Django 4.1.1 on 2022-09-29 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projectmanager", "0008_task_creator"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project", old_name="title", new_name="project_title",
        ),
    ]
