# Generated by Django 4.1.1 on 2022-09-29 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("projectmanager", "0009_rename_title_project_project_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="project",
            field=models.ForeignKey(
                db_column="project_title",
                on_delete=django.db.models.deletion.CASCADE,
                to="projectmanager.project",
            ),
        ),
    ]
